name: decision-transformer-atari
channels:
- pytorch
dependencies:
- python=3.8.11
- pytorch=1.12
- numpy
- psutil
- opencv
- pip
- pip:
  - atari-py
  - pyprind
  - tensorflow-gpu>=1.13
  - absl-py
  - atari-py
  - gin-config
  - gym
  - tqdm
  - blosc
  - git+https://github.com/google/dopamine.git
